export const LOAD_COUNTRIES = 'LOAD COUNTRIES';
export const SEARCH_COUNTRIES = 'SEARCH COUNTRIES';
export const DETAIL_COUNTRY = 'DETAIL CONUTRY';
export const ORDER_BY_NAME= 'ORDER TO LOWEST';
export const ORDER_BY_POPULATION = 'ORDER BY POPULATION';
export const FILERT_BY_CONTINENT ='FILTER BY CONTINENT'