export const LOAD_COUNTRIES = 'LOAD COUNTRIES';
export const SEARCH_COUNTRIES = 'SEARCH COUNTRIES';
export const DETAIL_COUNTRY = 'DETAIL CONUTRY';
export const MAJOR_ORDER = 'MAJOR ORDER';
export const ORDER_lOWEST= 'ORDER TO LOWEST';
export const POPULATION_MAJOR  = 'POPULATION MAJOR';
export const POPULATION_LOWEST = 'POPULATION_lOWEST'